_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.18.6
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
batch_size:
    value: 16
checkpoint_dir:
    value: /csghome/hpdc04/Transformer_Code/checkpoints
context_length:
    value: 256
data_dir:
    value: /csghome/hpdc04/Transformer_Code/CUPY/datasets/tokenized
epochs:
    value: 14
eval_interval:
    value: 100
eval_iters:
    value: 200
gradient_accumulation_steps:
    value: 32
log_interval:
    value: 100
lr:
    value: 0.1
seed:
    value: 1
vocab_file:
    value: /csghome/hpdc04/Transformer_Code/CUPY/models/tokenizers/goe_pt/goe_pt_tokenizer.json
