export context_length=1024
export epochs=100
export batch_size=6
export eval_interval=25 # default : 100
export lr=0.5 # Learning Rate
export log_interval=100 #default : 100
export n_heads=4 # Number of heads in MultiHeadAttention
export dropout=0
export tokenizer="/csghome/hpdc04/Transformer_Code/CUPY/models/tokenizers/tokenizer_512.json"
export n_layer=8
export n_embd=384